#version 440 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

//layout(binding = 0, rgba32f) uniform image2D currDispTex;
//layout(binding = 1, rgba32f) uniform image2D prevDispTex;

layout(std430, binding = 3) buffer boat
{
	vec4 voxels[16*16*16];
};

uniform isampler3D voxels;

uniform sampler2D dispTex;

uniform float fftSize;
uniform float waterSize;
uniform float waterScale;

uniform float dt;


void main()
{
	ivec3 i = ivec2(gl_GlobalInvocationID.xyz);
	

}